import { MarinaAmenity } from "@/types/marina"
import { Icon } from "@iconify/react"

export const amenityIcons: Record<MarinaAmenity, string> = {
  fuel: "mdi:fuel",
  water: "mdi:water",
  electricity: "mdi:flash",
  wifi: "mdi:wifi",
  restaurant: "mdi:silverware-fork-knife",
  supermarket: "mdi:cart",
  laundry: "mdi:washing-machine",
  shower: "mdi:shower",
  security: "mdi:shield-check",
  repair: "mdi:wrench",
  parking: "mdi:car-parking-lights",
  atm: "mdi:cash",
  crane: "mdi:crane",
  mobile_crane: "mdi:truck-fast",
  diving_service: "mdi:diving-scuba-tank",
  fire_service: "mdi:fire-truck",
  waste_collection: "mdi:trash-can",
  mooring: "mdi:anchor",
  haul_out: "mdi:ferry",
  recycling: "mdi:recycle",
  transit_log: "mdi:file-document-outline",
  boat_rental: "mdi:sail-boat",
  car_rental: "mdi:car",
  fire_suppression: "mdi:fire-extinguisher",
  blue_card: "mdi:card-account-details",
  first_aid: "mdi:medical-bag",
  dishwashing: "mdi:dishwasher",
  hotel: "mdi:hotel",
  bar: "mdi:glass-cocktail",
  entertainment: "mdi:party-popper",
  pool: "mdi:pool",
}