export const amenityLabels: Record<string, string> = {
    fuel: "Yakıt",
    water: "Su",
    electricity: "Elektrik",
    wifi: "WiFi",
    restaurant: "Restoran",
    supermarket: "Market",
    laundry: "Çamaşırhane",
    shower: "Duş",
    security: "Güvenlik",
    repair: "Tamir",
    parking: "Otopark",
    atm: "ATM",
    crane: "Vinç",
    diving_service: "Dalış Hizmeti",
    fire_service: "Acil Yangın Müdahalesi",
    waste_collection: "Atık Toplama",
    mooring:"Palamar Hizmeti",
    mobile_crane: "Mobil Vinç",
    haul_out: "Çekek Hizmeti",
  }